### ISSUE TITLE
Package does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by MGeurts** [liberu-genealogy/laravel-gedcom#2]
During installation of the package ( composer require familytree365/laravel-gedcom ) in a fresh LARAVEL 10 project, the following warnings occure:

`Class FamilyTree365\LaravelGedcom\Facades\GedcomParserFacade located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Facades\GedcomExpFacade.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Addr located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Addr.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Fam\Caln located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Caln.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Chan located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Chan.php does not comply with psr-4 autoloading standard. Skipping.                                            
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Date located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Date.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Fam\Even located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Fam\Even.php does not comply with psr-4 autoloading standard. Skipping. 
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Fam\Slgs located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Fam\Slgs.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Alia located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Alia.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Anci located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Anci.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Asso located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Asso.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Desi located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Desi.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Even\Plac located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Even\Plac.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Even located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Even.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Lds located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Lds.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Name\Fone located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Name\Fone.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Name\Romn located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Name\Romn.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Name located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Name.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Indi\Subm located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Indi\Subm.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Note located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Note.php does not comply with psr-4 autoloading standard. Skipping.                                            
Class FamilyTree365\LaravelGedcom\Utils\Exporter\NoteRef located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\NoteRef.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Obje located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Obje.php does not comply with psr-4 autoloading standard. Skipping.                                            
Class FamilyTree365\LaravelGedcom\Utils\Exporter\ObjeRef\File located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\ObjeRef\File.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\ObjeRef located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\ObjeRef.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Phon located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Phon.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Refn located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Refn.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Repo located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Repo.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\RepoRef located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\RepoRef.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Sour\Data\Even located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Sour\Data\Even.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Sour\Data located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Sour\Data.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Sour\Repo located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Sour\Repo.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Sour located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Sour.php does not comply with psr-4 autoloading standard. Skipping.                                            
Class FamilyTree365\LaravelGedcom\Utils\Exporter\SourRef\Even located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\SourRef\Even.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\SourRef located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\SourRef.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Subm located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Subm.php does not comply with psr-4 autoloading standard. Skipping.
Class FamilyTree365\LaravelGedcom\Utils\Exporter\Subn located in D:/LARAGON/www/gedcom-import/vendor/familytree365/laravel-gedcom/src\Utils\exporter\Subn.php does not comply with psr-4 autoloading standard. Skipping.`

**Comment by boscan-alexandru** [comment]
I have created a pull request and it **should be solved as soon as it merges** into the main branch --> https://github.com/liberu-genealogy/laravel-gedcom/pull/3

**Comment by MGeurts** [comment]
Thanks
